version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: America/New_York
  open-pull-requests-limit: 10
