---
ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - fastlane/*
          - Dangerfile
          - Gemfile
          - .circleci/*
          - .ruby-version
          - .swift-version
          - Makefile
          - .github/*
tests:
  - changed-files:
      - any-glob-to-any-file:
          - Tests/*
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - Package.swift
          - Package.resolved
          - .gitmodules
          - Brewfile
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - doc/*
          - Documentation/*
          - CHANGELOG.md
framework:
  - changed-files:
      - any-glob-to-any-file:
          - Sources/*
