---
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'bug 🐛'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
      - 'security'
      - 'dependencies'
  - title: '💯 CI/CD'
    labels:
      - 'CI/CD'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
