---
name: Automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.8.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "automerge, !WIP, !wip,!work in progress, !PR: unreviewed"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_RETRIES: "2"
          UPDATE_LABELS: "automerge"
