---
name: Labeler
on: [pull_request_target]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        sync-labels: true
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
